window.LEVELS = [
  {
    id: "rocket",
    name: "Workshop Rocket",
    subtitle: "Training build for new launch engineers.",
    objective: "Assemble the rocket by placing the body, nose cone, left fin, and right fin.",
    environmentColor: "#d9efe8",
    bestTimeKey: "vr-assembly-best-rocket",
    scoreTargets: { threeStar: 24, twoStar: 38 },
    partTrayLabel: "Training Parts",
    parts: [
      {
        id: "body",
        label: "Rocket Body",
        primitive: "a-box",
        color: "#d1495b",
        position: "-4.8 1.7 -0.45",
        size: { width: 0.7, height: 2.0, depth: 0.7 },
        target: {
          primitive: "a-box",
          position: "1.5 2.0 0",
          size: { width: 0.7, height: 2.0, depth: 0.7 },
        },
      },
      {
        id: "nose",
        label: "Nose Cone",
        primitive: "a-cone",
        color: "#f77f00",
        position: "-3.95 2.15 -0.35",
        radiusBottom: 0.42,
        radiusTop: 0.02,
        height: 0.75,
        target: {
          primitive: "a-cone",
          position: "1.5 3.35 0",
          radiusBottom: 0.42,
          radiusTop: 0.02,
          height: 0.75,
        },
      },
      {
        id: "fin-left",
        label: "Left Fin",
        primitive: "a-box",
        color: "#457b9d",
        position: "-4.1 1.15 0.25",
        size: { width: 0.18, height: 0.72, depth: 0.55 },
        rotation: "0 0 24",
        target: {
          primitive: "a-box",
          position: "1.08 1.3 0",
          size: { width: 0.18, height: 0.72, depth: 0.55 },
          rotation: "0 0 24",
        },
      },
      {
        id: "fin-right",
        label: "Right Fin",
        primitive: "a-box",
        color: "#457b9d",
        position: "-4.55 1.15 0.6",
        size: { width: 0.18, height: 0.72, depth: 0.55 },
        rotation: "0 0 -24",
        target: {
          primitive: "a-box",
          position: "1.92 1.3 0",
          size: { width: 0.18, height: 0.72, depth: 0.55 },
          rotation: "0 0 -24",
        },
      },
    ],
  },
  {
    id: "rover",
    name: "Mars Rover",
    subtitle: "Precision assembly under expedition pressure.",
    objective: "Build the rover frame, scanner mast, battery pod, and antenna dish.",
    environmentColor: "#f5e3c5",
    bestTimeKey: "vr-assembly-best-rover",
    scoreTargets: { threeStar: 30, twoStar: 46 },
    partTrayLabel: "Rover Bay",
    parts: [
      {
        id: "frame",
        label: "Frame",
        primitive: "a-box",
        color: "#577590",
        position: "-4.8 1.48 -0.45",
        size: { width: 1.3, height: 0.26, depth: 1.8 },
        target: {
          primitive: "a-box",
          position: "1.5 1.18 0",
          size: { width: 1.3, height: 0.26, depth: 1.8 },
        },
      },
      {
        id: "battery",
        label: "Battery Pod",
        primitive: "a-box",
        color: "#f9c74f",
        position: "-4.15 1.82 0.25",
        size: { width: 0.5, height: 0.5, depth: 0.5 },
        target: {
          primitive: "a-box",
          position: "1.1 1.52 0.2",
          size: { width: 0.5, height: 0.5, depth: 0.5 },
        },
      },
      {
        id: "mast",
        label: "Scanner Mast",
        primitive: "a-cylinder",
        color: "#43aa8b",
        position: "-3.7 1.7 -0.2",
        radius: 0.12,
        height: 1.0,
        target: {
          primitive: "a-cylinder",
          position: "1.55 1.72 0.05",
          radius: 0.13,
          height: 1.0,
        },
      },
      {
        id: "dish",
        label: "Antenna Dish",
        primitive: "a-cone",
        color: "#f3722c",
        position: "-4.55 2.05 0.55",
        radiusBottom: 0.35,
        radiusTop: 0.05,
        height: 0.45,
        rotation: "180 0 0",
        target: {
          primitive: "a-cone",
          position: "1.55 2.28 0.05",
          radiusBottom: 0.35,
          radiusTop: 0.05,
          height: 0.45,
          rotation: "180 0 0",
        },
      },
    ],
  },
  {
    id: "drone",
    name: "Cargo Drone",
    subtitle: "Fast assembly for the busiest shift in the workshop.",
    objective: "Build the drone body, left arm, right arm, and sensor core.",
    environmentColor: "#dbe9ff",
    bestTimeKey: "vr-assembly-best-drone",
    scoreTargets: { threeStar: 26, twoStar: 40 },
    partTrayLabel: "Drone Components",
    parts: [
      {
        id: "core",
        label: "Drone Body",
        primitive: "a-box",
        color: "#3d5a80",
        position: "-4.6 1.55 -0.15",
        size: { width: 0.95, height: 0.35, depth: 0.95 },
        target: {
          primitive: "a-box",
          position: "1.5 1.25 0",
          size: { width: 0.95, height: 0.35, depth: 0.95 },
        },
      },
      {
        id: "arm-left",
        label: "Left Arm",
        primitive: "a-box",
        color: "#98c1d9",
        position: "-4.05 1.82 0.45",
        size: { width: 1.0, height: 0.12, depth: 0.12 },
        target: {
          primitive: "a-box",
          position: "0.82 1.25 0",
          size: { width: 1.0, height: 0.12, depth: 0.12 },
        },
      },
      {
        id: "arm-right",
        label: "Right Arm",
        primitive: "a-box",
        color: "#98c1d9",
        position: "-4.05 1.58 0.7",
        size: { width: 1.0, height: 0.12, depth: 0.12 },
        target: {
          primitive: "a-box",
          position: "2.18 1.25 0",
          size: { width: 1.0, height: 0.12, depth: 0.12 },
        },
      },
      {
        id: "sensor",
        label: "Sensor Core",
        primitive: "a-sphere",
        color: "#ee6c4d",
        position: "-3.85 1.55 -0.55",
        radius: 0.24,
        target: {
          primitive: "a-sphere",
          position: "1.5 1.62 0",
          radius: 0.24,
        },
      },
    ],
  },
];
